### ISSUE TITLE
Actualización de Documentación

### ISSUE THREAD

**Issue by Blap00** [Blap00/GymGPT-API#22]

**Comment by Blap00** [comment]
Actualizado Diagrama de Clases, @MoonLight-coder realiza el Check

**Comment by Blap00** [comment]
Actualizando Diagrama de Comunicación

**Comment by Blap00** [comment]
@MoonLight-coder Trabajar Vista Despliegue y procesos (Componentes, paquetes, Actividad) Escribir apenas tengas alguna que otra lista para echar el ojo y revisar

**Comment by Blap00** [comment]
@Blap00 Trabajar vista Logica y Fisica (Clases, Comunicación, Secuencia, Despliegue) Escribir los avances para que revise @MoonLight-coder

**Comment by Blap00** [comment]
> Actualizando Diagrama de Comunicación

Actualizado Diagrama, revisar @MoonLight-coder

**Comment by Blap00** [comment]
> [@Blap00](https://github.com/Blap00) Trabajar vista Logica y Fisica (Clases, Comunicación, Secuencia, Despliegue) Escribir los avances para que revise [@MoonLight-coder](https://github.com/MoonLight-coder)

Actualizado Diagrama de Secuencia, revisar @MoonLight-coder

**Comment by Blap00** [comment]
Diagrama de Despliegue revisado y sin cambios pendientes

**Comment by MoonLight-coder** [comment]
Diagrama de Componentes Realizado, revisar @Blap00

**Comment by MoonLight-coder** [comment]
Diagrama de Actividades/Camara Realizado, revisar @Blap00
